#!/usr/bin/env python3
"""Remove duplicate SVG image from Big Bang page that was generated by agent"""
import re

# Read the file
with open('encyclopedia/big-bang.html', 'r') as f:
    html = f.read()

# Remove the first concept-visual figure (the SVG one generated by agent)
# Pattern: from the encyclopedia-hero closing div to the first figure
pattern = r'(</div></div>)<figure class="concept-visual"><img src="/assets/images/encyclopedia/big-bang\.svg"[^>]*>[^<]*(?:<figcaption>[^<]*(?:<span[^>]*>[^<]*</span>)?[^<]*</figcaption>)?</figure>'

html = re.sub(pattern, r'\1', html, count=1)

# Write back
with open('encyclopedia/big-bang.html', 'w') as f:
    f.write(html)

print("Removed duplicate SVG image")
