theory_path: Empirical Measurement of Reality.txt
template_path: ENCYCLOPEDIA-TEMPLATE.md
index_dir: agents/encyclopedia/.index
model: gpt-5
fallback_model: gpt-4o-mini
reasoning_effort: high
verbosity: high
allow_fallback: false
embedding_model: text-embedding-3-small
chunk_size: 1400
chunk_overlap: 200
retrieve_k: 8
max_tokens: 3000
