name: Build LaTeX PDFs (targeted)

on:
  workflow_dispatch:
  push:
    paths:
      - 'rs-website/papers/Inevitable-framework.tex'
      - 'rs-website/papers/empirical-measurement-of-reality.tex'
      - 'rs-website/.github/workflows/latex-pdfs.yml'

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TeX Live (minimal set)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-science lmodern latexmk

      - name: Compile PDFs
        run: |
          set -e
          cd rs-website/papers
          latexmk -pdf -interaction=nonstopmode -halt-on-error Inevitable-framework.tex || true
          latexmk -pdf -interaction=nonstopmode -halt-on-error empirical-measurement-of-reality.tex || true

      - name: Commit PDFs if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rs-website/papers/Inevitable-framework.pdf rs-website/papers/empirical-measurement-of-reality.pdf || true
          if ! git diff --cached --quiet; then
            git commit -m "ci: build PDFs for Inevitable-framework and Empirical Measurement"
            git push
          else
            echo "No PDF changes to commit."
          fi


